object Versions {
    const val retrofit = "2.9.0"
    const val moshi = "2.9.0"
    const val interceptor = "4.2.1"
    const val hilt = "2.41"
    const val hiltNavigation = "1.0.0"
    const val coil = "2.0.0-rc01"
    const val pager = "0.23.0"
    const val insets = "0.23.0"
    const val compose = "1.0.1"
    const val runtimeKtx = "2.3.1"
    const val activityCompose = "1.3.1"
    const val junit = "4.13.2"
    const val extJunit = "1.1.3"
    const val espresso = "3.4.0"
    const val androidGradlePlugin = "7.1.2"
    const val kotlin = "1.5.21"
    const val coreKtx = "1.7.0"
    const val ktor = "1.6.8"
}
